# Generated by Django 2.2.8 on 2019-12-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
